// Airline code to name mapping
export const airlineNames = {
  'AA': 'American Airlines',
  'BA': 'British Airways',
  'DL': 'Delta Air Lines',
  'UA': 'United Airlines',
  'LH': 'Lufthansa',
  'AF': 'Air France',
  'KL': 'KLM Royal Dutch Airlines',
  'VS': 'Virgin Atlantic',
  'EK': 'Emirates',
  'QR': 'Qatar Airways',
  'SQ': 'Singapore Airlines',
  'CX': 'Cathay Pacific',
  'QF': 'Qantas',
  'IB': 'Iberia',
  'LX': 'Swiss International Air Lines',
  'OS': 'Austrian Airlines',
  'SN': 'Brussels Airlines',
  'TP': 'TAP Air Portugal',
  'AZ': 'Alitalia',
  'EI': 'Aer Lingus',
  'FI': 'Icelandair',
  'SK': 'SAS Scandinavian Airlines',
  'TK': 'Turkish Airlines',
  'SU': 'Aeroflot',
  'LO': 'LOT Polish Airlines',
  'LX': 'Swiss',
  'LX': 'Swiss International',
  'FR': 'Ryanair',
  'U2': 'easyJet',
  'EW': 'Eurowings',
  'DY': 'Norwegian Air Shuttle',
  'VY': 'Vueling',
  'HV': 'Transavia',
  'PC': 'Pegasus Airlines',
  'W6': 'Wizz Air',
  'BE': 'Flybe',
  'LS': 'Jet2.com',
  'BY': 'TUI Airways',
  'MT': 'Thomas Cook Airlines',
  'T3': 'Eastern Airways',
  'LM': 'Loganair',
  'SA': 'South African Airways',
  'ET': 'Ethiopian Airlines',
  'MS': 'EgyptAir',
  'RJ': 'Royal Jordanian',
  'GF': 'Gulf Air',
  'EY': 'Etihad Airways',
  'SV': 'Saudi Arabian Airlines',
  'KU': 'Kuwait Airways',
  'OM': 'Miat Mongolian Airlines',
  'PK': 'Pakistan International Airlines',
  'AI': 'Air India',
  '9W': 'Jet Airways',
  'SG': 'SpiceJet',
  '6E': 'IndiGo',
  'CA': 'Air China',
  'MU': 'China Eastern Airlines',
  'CZ': 'China Southern Airlines',
  'JL': 'Japan Airlines',
  'NH': 'All Nippon Airways',
  'KE': 'Korean Air',
  'OZ': 'Asiana Airlines',
  'TG': 'Thai Airways',
  'VN': 'Vietnam Airlines',
  'GA': 'Garuda Indonesia',
  'MH': 'Malaysia Airlines',
  'PR': 'Philippine Airlines',
  'QF': 'Qantas',
  'NZ': 'Air New Zealand',
  'FJ': 'Fiji Airways',
  'HA': 'Hawaiian Airlines',
  'AS': 'Alaska Airlines',
  'B6': 'JetBlue Airways',
  'WN': 'Southwest Airlines',
  'F9': 'Frontier Airlines',
  'NK': 'Spirit Airlines',
  'G4': 'Allegiant Air',
  'AC': 'Air Canada',
  'WS': 'WestJet',
  'PD': 'Porter Airlines',
  'AM': 'Aeromexico',
  'CM': 'Copa Airlines',
  'AV': 'Avianca',
  'LA': 'LATAM Airlines',
  'JJ': 'LATAM Brasil',
  'G3': 'Gol Transportes Aéreos',
  'AD': 'Azul Brazilian Airlines',
  'AR': 'Aerolineas Argentinas',
  'LP': 'LATAM Peru',
  'LA': 'LATAM Chile',
  'LA': 'LATAM Colombia',
  'LA': 'LATAM Ecuador',
  'LA': 'LATAM Paraguay'
}

export const getAirlineName = (code) => {
  if (!code) return 'Unknown Airline'
  const upperCode = code.toUpperCase()
  return airlineNames[upperCode] || code
}

